<?php

namespace App\Enums\Otp;

enum OtpTypeEnum: string
{
    case EMAIL_REGISTER_OTP = 'EMAIL_REGISTER_OTP';
    case PASSWORDLESS_LOGIN_OTP = 'PASSWORDLESS_LOGIN_OTP';
    case EMAIL_VERIFICATION_OTP = 'EMAIL_VERIFICATION_OTP';
    case PHONE_VERIFY_OTP = 'PHONE_VERIFY_OTP';
    case PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP';
}
